### ISSUE TITLE
Runtime Environment

### ISSUE THREAD

**Issue by Gracccce** [youquand/BertForQuestionAndAnswering-On-SquadV2#1]
Thanks for your code! I ran it on my computer, but I didn't get the same scores. Can I ask you for the runtime environment?

**Comment by toandnh** [comment]
Sorry, I accidentally deleted that conda environment a couple months back. All I remember using is python 3.9. Can I ask what scores you got? We might be able to figure this out here.

**Comment by Gracccce** [comment]
Thanks for your information, I've solved my problem. I change python 3.7. to python 3.8, and it works.
